final Map<String, String> clueBank = {
  "spear": "Targeted at individuals",
  "urgency": "Used in phishing emails to make users act fast",
  "https": "Sometimes used to fake a secure connection",
  "vishing": "Use of voice calls",
  "smishing": "SMS or texts related",
  "spoofed": "Fake site that looks real",
  "ransomware": "locks files and demands payment",
  "payment": "Usually demanded in crypto after encryption",
  "backups": "Keeping copy of original files",
  "disconnect": "First step after infection: isolate device",
  "fbi": "FBI advises against paying ransom",
  "malware": "Malware is a general term for malicious software",
  "worm": "Worms can spreads without needing a host file.",
  "trojan": "Similar to Trojan Horse from Greek mythology",
  "spyware": "Silently monitors user activity",
  "adware": "Flooding with ADS!",
  "rootkit": "rootkits grants secret system access",
  "firewall": "It's a protective barrier",
  "updates": "Prevent malware by staying current.",
};