final Map<String, String> clueBank = {
  "login": "Never share your personal login details.",
  "unlock": "Legitimate services never ask money to unlock.",
  "money": "Never send money to unverified requests.",
  "attachment": "Unknown attachments may hide harmful content.",
  "download": "Only download apps from trusted stores.",
  "slow": "Sudden slowness may indicate something hidden running.",
  "usb": "Never trust USB devices from strangers.",
  "pop": "Excess pop-ups are signs of unwanted software.",
  "contacts": "Deny apps unnecessary access to personal info.",
  "prize": "If it sounds too good, check carefully.",
  "link": "Look closely at website addresses.",
  "locked": "Real companies rarely rush you.",
  "unexpected": "Be careful with things you didn’t ask for.",
  "http": "One small letter can mean less safety.",
  "gift": "Free things aren’t always free.",
  "habits": "Safe online habits protect you.",
  "safest": "Sometimes the safest option is prevention.",
  "situation": "Think of something holding files hostage.",
  "pay": "Paying may not solve the problem.",
  "habit": "Everyday routines affect your safety.",
  "spread": "Think who gains by tricking many people.",
  "slow": "Your computer’s behavior may reveal hidden issues.",
  "program": "Unwanted things installing themselves is suspicious.",
  "webcam": "Your camera should only turn on when you want it.",
  "infects your phone": "Look for odd or unusual phone behavior.",
  "reduce": "Good habits lower your risk.",
  "permission": "Why would a tool need more than its job?",
  "risky": "Some daily actions open the most doors to trouble.",
  "password": "Strangers don’t need private details.",
  "card": "Numbers can reveal more than you think.",
  "site": "Not all places are welcoming.",
  "safest": "Some choices bring less risk.",
  "quickly": "Speed is not always safety.",
  "address": "Look closer at where things come from.",
  "Bitcoin": "Odd payments are not normal.",
  "opened": "Closed things may be held back.",
  "invoice": "One step may trigger a chain.",
  "asking": "It wants something valuable from you.",
  "external": "Copies outside stay separate.",
  "ads": "Things that appear on their own can mean trouble.",
  "account": "Your name may act without you.",
  "icons": "Not everything looks as it seems.",

};