final Map<String, String> clueBank = {
  "fake": "Is it fake/real?",
  "suspicious": "Something is not right confirmation required",
  "login": "Someone is asking for your credentials",
  "spear": "Targeted at specific individuals",
  "vishing": "Ring Ring Ring",
  "files locked": "Your data cannot be accessed suddenly",
  "pay": "They want money to unlock something",
  "computer shows ransom": "A message demands payment to access files",
  "sudden file encryption": "Files are locked and inaccessible",
  "RaaS": "Illegal Service",
  "runs secretly": "Program running without your knowledge",
  "slows suddenly": "Computer becomes very slow unexpectedly",
  "popups": "Unwanted advertisement starts showing up",
  "primary goal": "What do attackers usually want from you?",
  "Smishing": "It's like phishing but on your phone",
  "main function of ransomware": "Think about what happens to your files",
  "attack vector": "How does it usually get to your device?",
  "demand after encrypting": "What do they want in return for your data?",
  "malware stands for": "Something harmful",
  "spreads without a host": "It doesn't need to attach to another file",
  "spyware function": "What does it secretly track?",
  "avoid malware infection": "How can you stay safe from harmful programs?",
  "pretends to be useful app": "Looks legit but is actually harmful",
  "collects user information": "Spies on you without permission",
  "floods screen with ads": "Annoying pop-ups everywhere",
  "unknown software installed": "Something appeared on your system unexpectedly",
  "NOT a common phishing vector": "One of these doesn’t belong",
  "psychological trick": "Threaten or immediate actions",
  "fake website designed to look real": "It mimics a legit site",
  "good prevention strategy": "One option is obviously unsafe",
  "first to use cryptocurrency payments": "Made headlines in 2013",
  "malware provides ongoing privileged access": "Hide and spy",
  "type of malware disguises itself": "Looks legit but isn’t",
};